# SERVER 1: Main Server (normal tests)
server {
    listen 8080;
	host 127.0.0.1;
    server_name localhost;
    root assets/;
    index index.html;
    client_max_body_size 5242880; # 5Mb

    error_page 400 401 403 404 405 error/40x.html;
	# error_page 404 error/405.html;

    # TEST: Directory Listing
	location /images {
		allow_methods GET;
		auto_index on;
	}

    # TEST: Directory Listing OFF
    location /images/private {
		allow_methods GET;
		auto_index off;
	}

    # TEST: File Uploads
    location /upload {
        allow_methods GET POST DELETE;
        auto_index on;
    }

    # TEST: Redirection 
    location /redirect {
        allow_methods GET POST;
        redirect http://localhost:8081/valid;
    }

    # TEST: Redirection 
    location /redirect1 {
        allow_methods GET POST;
        redirect /redirect2;
    }

    # TEST: Redirection 
    location /redirect2 {
        allow_methods GET POST;
        redirect /google;
    }

    # TEST: Redirection 
    location /google {
        allow_methods GET POST;
        redirect https://www.google.com;
    }

    # TEST: Python CGI
    location /cgi-py { 
        allow_methods GET POST;
        has_cgi true;
        cgi_path /usr/bin/python3;
        cgi_ext .py;
    }

    # TEST: PHP CGI
    location /cgi-php {
        allow_methods GET POST;
        has_cgi true;
        cgi_path /usr/bin/php-cgi;  
        cgi_ext .php;
    }
    # TEST: Method Not Allowed (to make tests if needed)
	location /valid {
		allow_methods GET POST;
		auto_index on;
	}
}

# SERVER 2: Strict Tests
server {
    listen 8081;
    server_name tests;
    root assets;
    index index.html;
    client_max_body_size 10; # Just 10 bytes to force error

    error_page 400 401 403 404 405 error/40x.html;

    # TEST: Method Not Allowed (to make tests if needed)
	location /valid {
		allow_methods GET POST;
		auto_index on;
	}
}