server {
    listen 8080;
    server_name localhost;
    root assets;
    index index.html;
    client_max_body_size 100;

    error_page 400 401 403 404 405 error/40x.html;

	location / {
		allow_methods GET;
	}

	location /post_body {
		allow_methods POST;
	}

    location /directory {
        allow_methods GET POST DELETE;
        root YoupiBanane;
        auto_index on;
    }
}
